app:
  domain: 'http://licron.com'
  port: '8088'
  dbtype: 'mysql'
  schedule: 'true'
log:
  dir: './logs/'
  format: 'json'

mysql:
  username: root
  password: 'root'
  path: '127.0.0.1:3306'
  dbname: 'go_test'
  config: 'charset=utf8&parseTime=True&loc=Local'
  maxidleconns: 10
  maxopenconns: 10
  logmode: true